#### 中间件配置
mysql:
  host: 182.92.239.63 #127.0.0.1
  port: 3306
  user: junjun
  password: jun.1998 #123456
  is_debug: true

redis:
  host: 182.92.239.63 #127.0.0.1
  port: 6379
  password: #123456
  db: 0

etcd:
  host: [127.0.0.1:2379]
  user: root
  password: root123456
  dail_time_out: 10
  dail_keep_alive_time: 10

grpc:
  call_time_out: 10 #秒


servers:
  gateway: "gateway"
  core: "core"
  queue: "queue"
  connect: "connect"


connect_port:
  nodes:
    node-1: "7933"
    node-2: "7934"
    node-3: "7935"
    node-4: "7936"
    ##["7933","7936","7934","7935"]
core_port:
  nodes:
    core-1: "5053"
    core-2: "5054"
    core-3: "5055"
    core-4: "5056"
  ##["5053","5054","5055","5056"]

jun_chat:
  nodes:
    node-1: "3501"
    node-2: "3502"
    node-3: "3503"
    node-4: "3504"
    ##["3501","3502","3503","3504"]